from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    AuthViewSet, GameViewSet, TransactionViewSet,
    ChatViewSet, RainViewSet, LeaderboardViewSet
)

router = DefaultRouter()
router.register(r'auth', AuthViewSet, basename='auth')
router.register(r'game', GameViewSet, basename='game')
router.register(r'transactions', TransactionViewSet, basename='transactions')
router.register(r'chat', ChatViewSet, basename='chat')
router.register(r'rain', RainViewSet, basename='rain')
router.register(r'leaderboard', LeaderboardViewSet, basename='leaderboard')

urlpatterns = [
    path('', include(router.urls)),
]

# Final URL patterns generated by the router:
#
# AUTH
#   POST   /api/auth/register/
#   POST   /api/auth/login/
#   POST   /api/auth/logout/
#   GET    /api/auth/me/
#   PATCH  /api/auth/update_profile/
#
# GAME
#   GET    /api/game/current/
#   GET    /api/game/history/
#   POST   /api/game/bet/
#   POST   /api/game/cashout/
#   GET    /api/game/my_bet/
#   GET    /api/game/my_history/
#
# TRANSACTIONS
#   GET    /api/transactions/list_transactions/
#   GET    /api/transactions/balance/
#   POST   /api/transactions/deposit/
#   POST   /api/transactions/complete_deposit/
#   POST   /api/transactions/withdraw/
#   GET    /api/transactions/check_deposit_status/?transaction_id=...
#
# CHAT
#   GET    /api/chat/messages/
#   POST   /api/chat/send/
#
# RAIN
#   GET    /api/rain/active/
#   POST   /api/rain/join/
#
# LEADERBOARD
#   GET    /api/leaderboard/top/